[env]
TERM = "xterm-256color"

[font]
size = 28

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window.padding]
x = 6
y = 0

[window]
decorations = "none"
dynamic_padding = true

[general]
import = [ "~/.config/alacritty/themes/catppuccin-latte.toml" ]