theme = "catppuccin_latte"

[editor]
true-color = true
line-number = "relative"
mouse = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection", ":w"]

[keys.insert]
esc = [":w", "normal_mode"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
